### ISSUE TITLE
The training hyperparameters for 5x5 input?

### ISSUE THREAD

**Issue by Aithusa1113** [racso10/LFHSR#2]
Hi,
Thanks for sharing your work! I tried to train your method using 5x5 LF, view_n_new=5 but got a very low performance. I just ran "python train.py -S 4 -N 5 -dmin 4 -dmax 4 -dg 0.25 -l1 6 -l2 6 -l3 6 -l4 3 -b 4 -crop 32 -lr 0.001 -step 1600 -g 0" for training.
Do you have any idea what is wrong with the hyperparameters?

**Comment by racso10** [comment]
Hi, sorry for this mistake.
The parameter of `dmin` should be set with a negative value (-4).
We have fixed this bug.
Thanks very much!
